version: "3.9"
services:
  neteaseapi:
    build:
      dockerfile: Dockerfile.neteaseapi
    expose:
      - 3000
  qqmusicapi:
    build:
      dockerfile: Dockerfile.qqmusicapi
    environment:
      QQ: "" # don't forget this
    expose:
      - 3300
  frontend:
    build:
      dockerfile: Dockerfile.frontend
    expose:
      - 3000
  backend:
    build:
      dockerfile: Dockerfile.backend
    environment:
      MusicApi:NeteaseCloudMusic:Enabled: "true"
      MusicApi:NeteaseCloudMusic:ApiServerUrl: "http://neteaseapi:3000"
      MusicApi:NeteaseCloudMusic:PhoneNo: ""
      MusicApi:QQMusic:Enabled: "true"
      MusicApi:QQMusic:ApiServerUrl: "http://qqmusicapi:3300"
      MusicApi:QQMusic:QQNo: "" # also set QQ number at line:12
      MusicApi:QQMusic:Cookie: ""
      FrontEndUrl: "http://frontend:3000"
    depends_on:
      - neteaseapi
      - qqmusicapi
    ports:
      - "2706:5000"
    tty: true
    restart: on-failure
