version: "3.9"
services:
  neteaseapi:
    build:
      dockerfile: Dockerfile.neteaseapi
    expose:
      - 3000
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "echo 'fetch(\"http://localhost:3000\")' | node"
        ]
      interval: 10s
      timeout: 5s
      retries: 3
  qqmusicapi:
    build:
      dockerfile: Dockerfile.qqmusicapi
    environment:
      QQ: ""
    expose:
      - 3300
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "echo 'fetch(\"http://localhost:3300\")' | node"
        ]
      interval: 10s
      timeout: 5s
      retries: 3
  frontend:
    build:
      dockerfile: Dockerfile.frontend
    expose:
      - 3000
  backend:
    build:
      dockerfile: Dockerfile.backend
    environment:
      MusicApi:NeteaseCloudMusic:ApiServerUrl: "http://neteaseapi:3000"
      MusicApi:NeteaseCloudMusic:PhoneNo: ""
      MusicApi:QQMusic:ApiServerUrl: "http://qqmusicapi:3300"
      MusicApi:QQMusic:QQNo: ""
      MusicApi:QQMusic:Cookie: ""
      FrontEndUrl: "http://frontend:3000"
    depends_on:
      neteaseapi:
        condition: service_healthy
      qqmusicapi:
        condition: service_healthy
    ports:
      - "2706:5000"
    tty: true
    restart: on-failure
